#!/usr/bin/env python3

import threading
import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError

try:
    import cv2
except ImportError as exc:
    cv2 = None
    rospy.logerr("cv2 import failed: {0}".format(exc))

try:
    import tkinter as tk
    from PIL import Image as PILImage, ImageTk
except ImportError as exc:
    tk = None
    rospy.logerr("tkinter or PIL import failed. Please run 'pip install Pillow': {0}".format(exc))

NODE_NAME = "vision_display_node"

class VisionDisplayNode(object):
    def __init__(self):
        rospy.init_node(NODE_NAME)

        if tk is None or cv2 is None:
            rospy.logerr("Missing required libraries. Shutting down node.")
            return

        self.bridge = CvBridge()
        self.latest_cv_image = None
        self.image_lock = threading.Lock()

        # Subscribe to the annotated topic generated by vision_node.py
        self.annotated_topic = rospy.get_param(
            "/chef_robot_assistant/camera_frame_topic_out",
            "/chef_robot_assistant/image_annotated"
        )

        self.image_subscriber = rospy.Subscriber(
            self.annotated_topic,
            Image,
            self.image_callback,
            queue_size=1,
            buff_size=2 ** 24
        )

        # Initialize Tkinter Window
        self.root = tk.Tk()
        self.root.title("Chef Robot Assistant - Ingredient Detection")
        self.root.protocol("WM_DELETE_WINDOW", self.on_close)

        # Label to hold the image
        self.image_label = tk.Label(self.root, text="Waiting for camera feed...")
        self.image_label.pack(padx=10, pady=10)

        # Start the GUI update loop (~33fps)
        self.root.after(30, self.update_gui)

        rospy.loginfo(
            "%s initialized, listening for annotated frames on %s", 
            NODE_NAME, 
            self.annotated_topic
        )

    def image_callback(self, ros_image):
        """Callback to receive the annotated image from vision_node.py"""
        try:
            # vision_node publishes the image as BGR8
            cv_image = self.bridge.imgmsg_to_cv2(ros_image, desired_encoding="bgr8")
            with self.image_lock:
                self.latest_cv_image = cv_image
        except CvBridgeError as exc:
            rospy.logwarn_throttle(5.0, "cv_bridge error in display node: {0}".format(exc))

    def update_gui(self):
        """Periodically check for new frames and update the Tkinter window"""
        if rospy.is_shutdown():
            self.root.destroy()
            return

        with self.image_lock:
            frame = self.latest_cv_image.copy() if self.latest_cv_image is not None else None

        if frame is not None:
            # Convert OpenCV's BGR format to RGB for PIL/Tkinter
            rgb_image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            pil_image = PILImage.fromarray(rgb_image)
            tk_image = ImageTk.PhotoImage(image=pil_image)

            # Update the label with the new image
            self.image_label.config(image=tk_image, text="")
            self.image_label.image = tk_image  # Keep a reference to prevent garbage collection

        # Schedule the next GUI update
        self.root.after(30, self.update_gui)

    def on_close(self):
        """Handle the Tkinter window 'X' button being clicked"""
        rospy.loginfo("Closing Tkinter window...")
        rospy.signal_shutdown("Tkinter window closed by user")
        self.root.destroy()

    def run(self):
        """Run the Tkinter main loop on the main thread"""
        if tk is not None:
            self.root.mainloop()

def main():
    try:
        node = VisionDisplayNode()
        node.run()
    except rospy.ROSInterruptException:
        pass

if __name__ == "__main__":
    main()